### ISSUE TITLE
protraits_genomes.sh file not found

### ISSUE THREAD

**Issue by arianccbasile** [Waschina/gapseqEval#1]
Good morning!! 
I cannot find the file protraits_genomes.sh in the CarbonSourceTest needed to download the genomes required. May you provide the file?

Best, 
Arianna Basile

**Comment by jotech** [comment]
Hi @arianccbasile 
Some files got mixed up; I uploaded the right ones! The download should work via `./dat/protraits_genomes_download.sh` now! Thanks for reporting

**Comment by arianccbasile** [comment]
Thank you very much :) 
May I also ask you how you go from the list of the metabolic reconstructions to the .RDS files that you read at the beginning of https://github.com/Waschina/gapseqEval/blob/main/CarbonSourceTest/CarbonSourceTest.R

Best,
Arianna Basile

**Comment by arianccbasile** [comment]
Kind of... I will try :) did you use the flag "compress='xz' " inside saveRDS?

Best,
Arianna Basile

**Comment by jotech** [comment]
I think so the model files should be compressed, yes! To be sure, you have seen the [link](https://github.com/Waschina/gapseqEval/blob/main/CarbonSourceTest/models/download.md) to the model files, haven't you?

**Comment by arianccbasile** [comment]
Yes, of course :D I've already tried your tutorial, I just wanted to add a new dataset.

Best, 
Arianna

**Comment by jotech** [comment]
I see! If this is a publicly available dataset I'm happy to hear about it in case you want to share :)

**Comment by arianccbasile** [comment]
Thank you for your interest :) Unfortunately, the dataset I am working on is not public yet. 

Best,
Arianna

**Comment by jotech** [comment]
alright :) feel free to contact us or open an issue when you encounter problems with gapseq
